version: "3.7"

services:
    db:
        image: postgres:15-alpine
        container_name: payments-db
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
        ports:
            - "5432:5432"

    api:
        container_name: payments-api
        build:
            context: ../image
            dockerfile: Dockerfile
        depends_on:
            - db
        env_file:
            - ../.env
        ports:
          - "8080:8080"
        volumes:
            - ../image/app:/app
